### PR TITLE
tvOS Support

### PR DESCRIPTION
**Pull request by dmiluski**
Additionally, it appears tvOS had an incorrect target device family. Which results in bootstrap failing, as well as Xcode being unable to show a relevant simulator for tvOS target support.

Before: (Value 4)
screen shot 2017-09-21 at 10 58 18 am

After: (Value 3)
screen shot 2017-09-21 at 10 58 13 am

### CODE REVIEW

**Comment by dmiluski** [comment]
@nicklockwood followup for tvOS support

**Comment by dmiluski** [comment]
Tested integration on my fork. Once this is in, Carthage bootstrap should be fully functional with the expected targets.

**Comment by dmiluski** [comment]
Hi @nicklockwood, would you mind merging this? Currently this requires me to run off of a fork, and would love to move back to this repo as master.

**Comment by nicklockwood** [comment]
Merged in 1.2.2

**Pull request closed without merging**
